[package]
name = "zigx"
version = "0.1.0"
edition = "2021"
description = "Fast glass system monitor for Linux"

[dependencies]
bytemuck = { version = "1", features = ["derive"] }
glyphon = "0.12"
libc = "0.2"
libloading = "0.8"
pollster = "0.4"
wgpu = "30"
winit = "0.30"

[profile.release]
lto = "thin"
codegen-units = 1
opt-level = 3
